### PR TITLE
ADD documentation, README.md and cleaned up a bit

### PR DESCRIPTION
**Pull request by felixbd**
Hi Stand-up Maths

This PR tries to make the Python program executable without having to import the functions in the terminal or other script.

I also added a little documentation and a `README.md`.

The last thing I did was to compress the source code a bit (I changed `if not n` from `if n == 0` and just `if n` from `if n == 1`) etc.

best regards
hopefully these changes are helpful

Felix D

### CODE REVIEW

**Comment by DHainzl** [comment]
As a total python noob, I'd love to have a "How to run" in the README.md to make this more accessible.

I found out that you can run Matts original version by doing

```
$ python3
>>> from JigsawInferenceGizmo import jig
>>> jig(1,1,1)
```

Do you think you could add this (and / or how to run your improved version) to the README.md?

**Comment by felixbd** [comment]
No problem buddy. I'll edit everything again a little and take your suggestion into account.

**Comment by felixbd** [comment]
See #3

**Comment by Morpheus636** [comment]
Just so you know, you don't have to make a new PR, new changes get added to the existing one.

**Comment by felixbd** [comment]
now I know, sorry

**Pull request closed without merging**
